CREATE TABLE tb_siswa (
	id_siswa INT IDENTITY(1,1) PRIMARY KEY,
	nis VARCHAR(10),
	nama VARCHAR(50),
	alamat VARCHAR(100),
	tgl_lahir DATE,
	j_kelamin VARCHAR(1)
);

ALTER TABLE tb_siswa ALTER COLUMN j_kelamin VARCHAR(10);

INSERT INTO TB_SISWA(nis,nama,alamat,tgl_lahir,j_kelamin)
VALUES('10001','BEJO','SURABAYA','2010-10-06','PRIA');
INSERT INTO TB_SISWA(nis,nama,alamat,tgl_lahir,j_kelamin)
VALUES('10002','ANI','MALANG','2010-10-06','WANITA');

SELECT * FROM TB_SISWA

SELECT nama, tgl_lahir FROM TB_SISWA WHERE NIS = '10002';

SELECT * FROM TB_SISWA WHERE ALAMAT LIKE 'SU%'

SELECT * FROM TB_SISWA WHERE TGL_LAHIR BETWEEN '2010-10-05' AND '2010-10-10'

UPDATE TB_SISWA SET NAMA = 'BEJO SUTEDJO' WHERE NIS = '10001'

DELETE TB_SISWA WHERE NIS = '10002'